# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # Path to the solution file relative to the root of the project.
  SOLUTION_FILE_PATH: test/BedrockTest.sln

permissions:
  contents: read

jobs:
  build:
    name: Build
    runs-on: windows-latest
    strategy:
      matrix:
        config: [Debug, DebugOpt, Release]

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true

    - name: Generate Solution
      shell: cmd
      run: cd test && premake.bat

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Build
      run: msbuild /m /p:Configuration=${{ matrix.config }} ${{env.SOLUTION_FILE_PATH}}

    # Skip the tests in Release
    - if: ${{ matrix.config != 'Release' }}
      shell: cmd
      run: .\test\bin\x64\${{ matrix.config }}\BedrockTest${{ matrix.config }}.exe
    

